version: '3.1'
services:
  postgres:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "django", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  django:
    image: vicalmic/django-app:latest
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - 8000:8000
    depends_on:
      - postgres
  migrations:
    build: .
    image: vicalmic/django-app:latest
    command: python manage.py migrate
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
  users:
    build: .
    image: vicalmic/django-app:latest
    command: python manage.py createsuperuser --noinput
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
      - migrations

