version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5435:5434
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "django", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8078:8078
    depends_on:
      - postgres
  django:
    image: vicalmic/django-app:latest
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5435/postgres
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - 8001:8001
    depends_on:
      - postgres
  migrations:
    build: .
    image: vicalmic/django-app:latest
    command: python manage.py migrate
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5435/postgres
    depends_on:
      - postgres
  users:
    build: .
    image: vicalmic/django-app:latest
    command: python manage.py createsuperuser --noinput
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DATABASE_URL: postgres://postgres:postgres@postgres:5435/postgres
    depends_on:
      - postgres
      - migrations

